version: "3.8"

services:
  # Backed Configuration
  coupon_be:
    build:
      context: "./"
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./env.json:/usr/src/app/env.json:ro
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - postgres_db
      - redis

  # Database Configuration
  postgres_db:
    image: 'postgres:14.7'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: coupon_db
    volumes:
      - type: volume
        source: coupon-vol
        target: "/var/lib/postgresql/data"
        read_only: false

  # Redis Configuration
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass password
    restart: always
    volumes:
      - redis-vol:/data
    ports:
      - "6379:6379"

#  pgadmin:
#    image: 'dpage/pgadmin4:latest'
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=admin@domain.com
#      - PGADMIN_DEFAULT_PASSWORD=password
#    ports:
#      - "5050:80"

volumes:
  coupon-vol:
    name: coupon

  redis-vol:
    name: redis
